### ISSUE TITLE
Crashes on Mac OS

### ISSUE THREAD

**Issue by JosephBywater** [njb-said/blog#2]
On MacOS, when running nodemon, if there is not file `e.json` in the meta folder, website crashes.

Dates also show as Invalid. 
![screen shot 2017-07-23 at 20 45 07](https://user-images.githubusercontent.com/5558617/28502331-d70e5868-6fe7-11e7-8be0-e3e101f8ae25.png)

Maybe I installed it wrong? I did `npm install`

**Comment by njb-said** [comment]
I didn't put any checks in place for if a meta file doesn't exist, should be fixed if the json file exists.
I might add some safeguards in to protect against that at some point though 😛

**Comment by JosephBywater** [comment]
What about Invalid dates?

**Comment by njb-said** [comment]
They need to be in ISO format, to get the current date and time open a javascript console and type `new Date().toISOString()` and use that.

**Comment by JosephBywater** [comment]
Fixed in #3
